CREATE TABLE STUDENT (
    SNO VARCHAR2(255) NOT NULL ,
    SNAME VARCHAR2(255) NOT NULL ,
    SSEX CHAR(255) NOT NULL
);
INSERT INTO STUDENT VALUES ('001', 'KangKang', 'M ');
INSERT INTO STUDENT VALUES ('002', 'Mike', 'M ');
INSERT INTO STUDENT VALUES ('003', 'Jane', 'F ');