CREATE SCHEMA IF NOT EXISTS DB2ADMIN ;

CREATE TABLE DB2ADMIN.STUDENT (
    SNO VARCHAR2(255) NOT NULL ,
    SNAME VARCHAR2(255) NOT NULL ,
    SSEX CHAR(255) NOT NULL
);
INSERT INTO DB2ADMIN.STUDENT VALUES ('001', 'KangKang', 'M ');
INSERT INTO DB2ADMIN.STUDENT VALUES ('002', 'Mike', 'M ');
INSERT INTO DB2ADMIN.STUDENT VALUES ('003', 'Jane', 'F ');